"""Compliance documentation scaffolding (F6)."""

from __future__ import annotations

from pathlib import Path

DOCS_DIR = "aiact-compliance"

AI_POLICY = """# AI Usage Policy

> Generated by aiact-check. Template — review and adapt. Not legal advice.

## 1. Purpose

This policy governs the development, deployment, and use of AI systems in this
project, in line with Regulation (EU) 2024/1689 (the EU AI Act).

## 2. Scope

Applies to all AI features shipped from this repository, including third-party
AI services integrated via API.

## 3. Principles

- **Lawfulness**: no prohibited practices (Art. 5) — no social scoring, no
  manipulative techniques, no untargeted facial scraping, no emotion inference
  at work/school.
- **Transparency**: users are informed they interact with AI (Art. 50(1));
  synthetic content is marked machine-readably (Art. 50(2)); deepfakes are
  disclosed (Art. 50(4)).
- **Human oversight**: high-risk functions keep a human in the loop (Art. 14).
- **Data governance**: training/evaluation data quality and bias are examined
  (Art. 10).
- **AI literacy**: staff operating AI features receive adequate training (Art. 4).

## 4. Roles

| Role | Responsibility |
|------|----------------|
| Project owner | Compliance decisions, risk-tier review |
| Developers | Follow this policy; flag new AI features for re-scan |
| Reviewers | Verify AI features against this policy at PR review |

## 5. Review cadence

Re-run `aiact-check scan` on every release and after adding any AI capability.
Review this policy at least annually or when the risk classification changes.
"""

TECHNICAL_DOCUMENTATION = """# Technical Documentation (Annex IV skeleton)

> Generated by aiact-check. Required for HIGH-RISK systems (Art. 11).
> Template — complete every section before placing the system on the market.

## 1. General description
- Intended purpose of the system: _TODO_
- Version / release identifier: _TODO_
- Provider name and contact: _TODO_

## 2. Detailed description of system elements
- Architecture and components: _TODO_
- Model(s) used, origin (self-trained / third-party API / open weights): _TODO_
- Inputs and outputs, modalities: _TODO_
- Interactions with other systems: _TODO_

## 3. Development process
- Design decisions and methodologies: _TODO_
- Training / fine-tuning approach and data sources (if applicable): _TODO_
- Computational resources used: _TODO_
- Validation and testing procedures: _TODO_

## 4. Monitoring, functioning and control
- Human oversight measures (Art. 14): _TODO_
- Logging and traceability (Art. 12): _TODO_
- Accuracy, robustness, cybersecurity metrics (Art. 15): _TODO_

## 5. Risk management (Art. 9)
- Identified risks and mitigations: _TODO_
- Residual risk assessment: _TODO_

## 6. Data governance (Art. 10)
- Training/validation/testing datasets: origin, composition, cleaning: _TODO_
- Bias examination and mitigation: _TODO_

## 7. Changes during lifecycle
- Change log affecting compliance: _TODO_

## 8. EU declaration of conformity
- Applicable harmonised standards / common specifications: _TODO_
"""

TRANSPARENCY_NOTICE = """# Transparency Notice (Art. 50)

> Generated by aiact-check. Template — adapt to your user-facing surfaces.

## For conversational interfaces (Art. 50(1))

Display at first interaction:

> "You are chatting with an AI assistant. Responses are generated automatically
> and may be incorrect."

Exemption: only if it is obvious to a reasonably well-informed, observant and
circumspect person that they are interacting with AI. When in doubt, disclose.

## For synthetic content (Art. 50(2))

Mark AI-generated text/audio/image/video in a machine-readable format,
detectable at least as artificially generated or manipulated. Options:
- Metadata fields (e.g. EXIF/IPTC for images, ID3/custom tags for audio,
  C2PA credentials)
- Watermarking (audio/visible or invisible for images/video)
- API-level provenance headers for generated output

## For deepfakes (Art. 50(4))

Disclose that content has been artificially generated or manipulated, clearly
and at the latest at first interaction/exposure. For AI-generated text
published to inform the public on matters of public interest, disclose unless
there is human editorial review and responsibility.
"""

CHECKLIST_HEADER = """# EU AI Act Compliance Checklist

> Generated by aiact-check. Re-run `aiact-check scan` after changes.

"""


def _checklist_from_report(report: dict | None) -> str:
    lines = [CHECKLIST_HEADER]
    if not report:
        lines.append("_No scan report provided. Run `aiact-check scan --format json --output report.json`, then "
                     "`aiact-check init-docs --report report.json` to embed your live checklist._\n")
        lines.append("## General (all AI systems)")
        lines.append("- [ ] Art. 4: staff AI literacy")
        lines.append("- [ ] Re-scan on every release")
        return "\n".join(lines)
    cls = report.get("classification", {})
    tier = cls.get("tier", "unknown")
    lines.append(f"**Risk classification:** `{tier}`")
    lines.append("")
    for reason in cls.get("tierReasons", []):
        lines.append(f"- {reason}")
    lines.append("")
    obligations = report.get("obligations", [])
    if obligations:
        lines.append("## Obligations")
        for o in obligations:
            sev = " **[ACTION REQUIRED]**" if o.get("severity") == "action-required" else ""
            lines.append(f"- [ ] **{o.get('article')}** ({o.get('appliesTo')}, due {o.get('deadline')}){sev}")
            lines.append(f"      {o.get('text')}")
        lines.append("")
    findings = cls.get("findings", [])
    if findings:
        lines.append("## Findings to review")
        for f in findings:
            lines.append(f"- [{f.get('severity')}] {f.get('title')} — {f.get('article')}")
            if f.get("locations"):
                lines.append(f"      locations: {', '.join(f['locations'][:5])}")
        lines.append("")
    return "\n".join(lines)


TEMPLATES = {
    "AI_POLICY.md": AI_POLICY,
    "TECHNICAL_DOCUMENTATION.md": TECHNICAL_DOCUMENTATION,
    "TRANSPARENCY_NOTICE.md": TRANSPARENCY_NOTICE,
}


def init_docs(root: str | Path, force: bool = False, report: dict | None = None) -> tuple[list[str], list[str], list[str]]:
    """Create docs templates. Returns (created, skipped, errors)."""
    root = Path(root)
    target = root / DOCS_DIR
    created: list[str] = []
    skipped: list[str] = []
    errors: list[str] = []

    files = dict(TEMPLATES)
    files["CHECKLIST.md"] = _checklist_from_report(report)

    for name, content in files.items():
        path = target / name
        if path.exists() and not force:
            skipped.append(str(path))
            continue
        try:
            target.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
            created.append(str(path))
        except OSError as exc:
            errors.append(f"{path}: {exc}")
    return created, skipped, errors
